# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "gitlab"
  config.vm.hostname = "gitlab.localdomain"
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
  config.vm.network :forwarded_port, guest: 8983, host: 8983, auto_correct: true
  config.vm.network "private_network", ip: "192.168.56.101"
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.provider :parallels do |p, override|
    p.name = "gitlab"
    p.update_guest_tools = false
    p.optimize_power_consumption = false
    p.memory = 2048
    p.cpus = 2
  end

  config.vm.provider :vmware_workstation do |v, override|
    v.vmx["memsize"] = "1024"
    v.vmx["numvcpus"] = "1"
  end

  config.vm.provider "virtualbox" do |vb, override|
    vb.name = "gitlab"
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
    end
  end

  config.vm.provision :shell, :path => ".provisioner/setup_gitlab.sh"
end
