gitGraph
    commit
    commit
    branch fork/of/repository
    checkout fork/of/repository
    commit
    commit
    commit type:HIGHLIGHT tag:"Pull Request"
    checkout main
    merge fork/of/repository
