gitGraph
    commit id:"a11111"
    commit id:"b22222"
    branch local/main
    checkout local/main
    commit id:"y88888"
    commit id:"z99999"
    checkout main
    commit id:"c33333"
    commit id:"d44444"
