gitGraph
    commit
    commit
    branch fix/login-bug
    checkout fix/login-bug
    commit
    commit
    checkout main
    commit
    commit
    branch feature/new-logo
    checkout feature/new-logo
    commit
